Repository DimTeamWebserv/Webserv, pull requests merged in 2022-06, with the labels that each got.

#4 set .conf file & set location and server class
  config/default_tutorials.conf
  config/default_wiki.conf
  config/mine.conf
  config/nginx.conf
  config/our_default.conf
  includes/Config.hpp
  srcs/Config.cpp
  srcs/webserv.cpp
Labels: .conf, parsing

#9 EXAMPLE: add parsing exercise
  sujikim/config/default_tutorials.conf
  sujikim/config/default_wiki.conf
  sujikim/config/mine.conf
  sujikim/config/nginx.conf
  sujikim/config/our_default.conf
  sujikim/includes/Config.hpp
  sujikim/makefile
  sujikim/srcs/Config.cpp
  sujikim/srcs/Server.cpp
  sujikim/srcs/webserv.cpp
Labels: exercise

#13 [chore] : combine our code..
  ours/config/default_tutorials.conf
  ours/config/default_wiki.conf
  ours/config/mine.conf
  ours/config/nginx.conf
  ours/config/our_default.conf
  ours/includes/Config.hpp
  ours/includes/Server.hpp
  ours/includes/conffff.hpp
  ours/makefile
  ours/srcs/Config.cpp
  ours/srcs/Server.cpp
  ours/srcs/webserv.cpp
Labels: parsing

#14 Parsing structure modified.
  ours/config/our_default.conf
  ours/includes/Config.hpp
  ours/includes/Server.hpp
  ours/includes/conffff.hpp
  ours/srcs/Config.cpp
  ours/srcs/Server.cpp
  ours/srcs/webserv.cpp
Labels: parsing

#15 [fix] : modified parsing structure and merge with Develop branch
  README.md
  config/our_default.conf
  includes/Config.hpp
  includes/Server.hpp
  makefile
  srcs/Config.cpp
  srcs/Server.cpp
  srcs/webserv.cpp
  test.cpp
Labels: parsing

#16 [Add] add exec_server && class client
  config/our_default.conf
  includes/Client.hpp
  includes/Config.hpp
  includes/Server.hpp
  makefile
  srcs/Config.cpp
  srcs/exec_server.cpp
  srcs/webserv.cpp
Labels: execute, kqueue

#17 [Feat] parsing method, root, cgi
  srcs/Config.cpp
Labels: .conf, parsing

#19 [Feat] parsing return error_page
  includes/Config.hpp
  srcs/Config.cpp
Labels: .conf, parsing

#21 [feat] parsing index, auto_index, check auto_index
  includes/Config.hpp
  srcs/Config.cpp
Labels: parsing
